# Version: 7.17.3
elasticsearchHosts: "http://elasticsearch-master:9200"

ingress:
  enabled: true
  className: "nginx"
  pathtype: ImplementationSpecific
  hosts:
    - host: kibana.demo.io
      paths:
        - path: /

resources:
  requests:
    cpu: "200m"
    memory: "100Mi"
  limits:
    memory: "1Gi"