- debug: var=ansible_all_ipv4_addresses

- name: Disable systemd-resolved
  ansible.builtin.systemd:
    state: stopped
    enabled: false
    name: systemd-resolved

- name: Install dnsmasq
  ansible.builtin.shell: |
    unlink /etc/resolv.conf
    echo nameserver 8.8.8.8 | tee /etc/resolv.conf

- name: Update apt and install dnsmasq
  apt:
    name: dnsmasq
    state: latest
    update_cache: true

- name: Configure dnsmasq
  ansible.builtin.template:
    src: dnsmasq.conf.j2
    dest: /etc/dnsmasq.conf

- name: Configure resolve.conf
  ansible.builtin.template:
    src: resolv.conf.j2
    dest: /etc/resolv.conf

- name: Enable and start dnsmasq
  ansible.builtin.systemd:
    state: restarted
    enabled: true
    name: dnsmasq